# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(resolve:AWS_S3_BUCKET_NAME)%'
    filesystems:
        uploads_filesystem:
            adapter: uploads_adapter
