index:
    path: /
    controller: App\Controller\AppInfoController::appInfo
    methods: GET
register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: POST
api_login_check:
    path: /api/login_check
    methods: POST
places_get_all:
    path: /api/places
    controller: App\Controller\PlaceController::getPlacesAction
    methods: GET
place_get_details:
    path: /api/places/{place_id}
    controller: App\Controller\PlaceController::getPlaceDetailsAction
    requirements:
        place_id: '\d+'
    methods: GET
events_get_all:
    path: /api/events
    controller: App\Controller\EventController::getPublicEventsAction
    methods: GET
place_get_events:
    path: /api/places/{place_id}/events
    controller: App\Controller\PlaceController:getPlaceEventsAction
    methods: GET
group_get_events:
    path: /api/groups/{group_id}/events
    controller: App\Controller\GroupController:getGroupPrivateEventsAction
    methods: GET
event_create:
    path: /api/events
    controller: App\Controller\EventController::createPublicEventAction
    methods: POST
group_create_event:
    path: /api/groups/{group_id}/events
    controller: App\Controller\GroupController::createPrivateEventAction
    methods: POST
event_update:
    path: /api/events/{event_id}
    controller: App\Controller\EventController:updateEventAction
    methods: POST
events_get_upcoming:
    path: /api/events/upcoming
    controller: App\Controller\EventController:getUpcomingEventsAction
    methods: GET