index:
    path: /
    controller: App\Controller\AppInfoController::appInfo
    methods: GET
register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: POST
api_login_check:
    path: /api/login_check
    methods: POST
places_get_all:
    path: /api/places
    controller: App\Controller\PlaceController::getPlacesAction
    methods: GET
place_get_details:
    path: /api/places/{place_id}
    controller: App\Controller\PlaceController::getPlaceDetailsAction
    requirements:
        place_id: '\d+'
    methods: GET