# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_base_url: 'https://s3.amazonaws.com/%env(resolve:AWS_S3_BUCKET_NAME)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $uploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'
            $uploadedAssetsBaseUrl: '%uploads_base_url%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    #>AWS
    Aws\S3\S3Client:
        arguments:
            -
                version: 'latest'
                region: 'eu-central-1'
                credentials:
                    key: '%env(resolve:AWS_S3_ACCESS_ID)%'
                    secret: '%env(resolve:AWS_S3_ACCESS_SECRET)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\EventListener\JWTAuthSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onJWTAuthenticationSuccess}
    App\Serializer\FormExceptionNormalizer:
        tags: [ 'serializer.normalizer' ]
    App\Factory\NormalizerFactory:
        arguments: [ !tagged serializer.normalizer ]
        public: true
    App\Controller\ApiController:
        calls:
            - setLogger: ['@logger']
    App\Controller\AppInfoController:
        parent: App\Controller\ApiController
    App\Controller\EventController:
        parent: App\Controller\ApiController
    App\Controller\UserGroupController:
        parent: App\Controller\ApiController
    App\Controller\PlaceController:
        parent: App\Controller\ApiController
    App\Controller\SecurityController:
        parent: App\Controller\ApiController
    App\Controller\UserController:
        parent: App\Controller\ApiController
