version: "3"

services:
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
        volumes:
            - symfony_dockerized_app_sync:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - symfony_dockerized_app_sync:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local
    rabbitmq:
        build:
            context: ./rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq:cached
        networks:
            - symfony

volumes:
    symfony_dockerized_app_sync:
        external: true
    rabbitmq:

networks:
    symfony: