version: "3.3"

services:
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
        volumes:
            - symfony_dockerized_app_sync:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        depends_on:
            - php
        volumes:
            - symfony_dockerized_app_sync:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local
    rabbitmq:
        build:
            context: ./rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq:cached
        networks:
            - symfony
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 10s
            retries: 5

volumes:
    symfony_dockerized_app_sync:
        external: true
    rabbitmq:

networks:
    symfony: